// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0h9r5aBw3daTv88SqUUgjdDRA95NTMgc',
    appId: '1:278198449684:web:f875699284fd35422fd901',
    messagingSenderId: '278198449684',
    projectId: 'login-19610',
    authDomain: 'login-19610.firebaseapp.com',
    storageBucket: 'login-19610.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwWSWFPL6dVU9SLT1wP53Zv9M2673GXPU',
    appId: '1:278198449684:android:f423c9fdd79bd9112fd901',
    messagingSenderId: '278198449684',
    projectId: 'login-19610',
    storageBucket: 'login-19610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx4oHOEXPkwnUH0VIbQTbgBsLq5R2b2jI',
    appId: '1:278198449684:ios:d5f18c9ccb2018c02fd901',
    messagingSenderId: '278198449684',
    projectId: 'login-19610',
    storageBucket: 'login-19610.appspot.com',
    iosClientId: '278198449684-lnsdsg6c943rf8bntn0ggtktiiofimb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx4oHOEXPkwnUH0VIbQTbgBsLq5R2b2jI',
    appId: '1:278198449684:ios:d5f18c9ccb2018c02fd901',
    messagingSenderId: '278198449684',
    projectId: 'login-19610',
    storageBucket: 'login-19610.appspot.com',
    iosClientId: '278198449684-lnsdsg6c943rf8bntn0ggtktiiofimb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTable',
  );
}
